
// Auto-generated by Bot V3 at 2026-01-22T15:06:03.450509
const LIVE_MATCHES = [];
const UPCOMING_MATCHES = [
  {
    "id": "Vortex_vs_Zenith_21_23",
    "league": "Berserk League",
    "team1": "Vortex",
    "team2": "Zenith",
    "score": "0:0",
    "status": "UPCOMING",
    "time": "21-01-2026 23:49",
    "odds": {
      "p1": 1.72,
      "p2": 2.0
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "Evoker_vs_Zenith_21_23",
    "league": "Berserk League",
    "team1": "Evoker",
    "team2": "Zenith",
    "score": "0:0",
    "status": "UPCOMING",
    "time": "21-01-2026 23:58",
    "odds": {
      "p1": 2.05,
      "p2": 1.68
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "Havoc_vs_Ignis_22_02",
    "league": "Berserk League",
    "team1": "Havoc",
    "team2": "Ignis",
    "score": "0:0",
    "status": "UPCOMING",
    "time": "22-01-2026 02:18",
    "odds": {
      "p1": 1.68,
      "p2": 2.05
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "K3vlar_vs_L1nch_22_09",
    "league": "Berserk League",
    "team1": "K3vlar",
    "team2": "L1nch",
    "score": "0:0",
    "status": "UPCOMING",
    "time": "22-01-2026 09:08",
    "odds": {
      "p1": 1.02,
      "p2": 10.0
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "E0ris_vs_L1nch_22_09",
    "league": "Berserk League",
    "team1": "E0ris",
    "team2": "L1nch",
    "score": "0:0",
    "status": "UPCOMING",
    "time": "22-01-2026 09:15",
    "odds": {
      "p1": 2.3,
      "p2": 1.55
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "E0ris_vs_K3vlar_22_09",
    "league": "Berserk League",
    "team1": "E0ris",
    "team2": "K3vlar",
    "score": "0:0",
    "status": "UPCOMING",
    "time": "22-01-2026 09:36",
    "odds": {
      "p1": 2.15,
      "p2": 1.62
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "Myst_vs_Glare_22_14",
    "league": "Berserk League",
    "team1": "Myst",
    "team2": "Glare",
    "score": "0:0",
    "status": "UPCOMING",
    "time": "22-01-2026 14:02",
    "odds": {
      "p1": 1.58,
      "p2": 2.2
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "Glare_vs_Lancer_22_14",
    "league": "Berserk League",
    "team1": "Glare",
    "team2": "Lancer",
    "score": "0:0",
    "status": "UPCOMING",
    "time": "22-01-2026 14:11",
    "odds": {
      "p1": 1.88,
      "p2": 1.82
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  }
];
const MATCH_HISTORY = [
  {
    "id": "Glare_vs_Lancer_22_13",
    "league": "Berserk League",
    "team1": "Glare",
    "team2": "Lancer",
    "score": "7:13",
    "status": "FINISHED",
    "time": "22-01-2026 13:17",
    "odds": {
      "p1": 1.9,
      "p2": 1.8
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team2"
  },
  {
    "id": "Myst_vs_Glare_22_13",
    "league": "Berserk League",
    "team1": "Myst",
    "team2": "Glare",
    "score": "13:7",
    "status": "FINISHED",
    "time": "22-01-2026 13:08",
    "odds": {
      "p1": 1.62,
      "p2": 2.15
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Myst_vs_Lancer_22_12",
    "league": "Berserk League",
    "team1": "Myst",
    "team2": "Lancer",
    "score": "8:13",
    "status": "FINISHED",
    "time": "22-01-2026 12:15",
    "odds": {
      "p1": 2.2,
      "p2": 1.58
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team2"
  },
  {
    "id": "Glare_vs_Lancer_22_12",
    "league": "Berserk League",
    "team1": "Glare",
    "team2": "Lancer",
    "score": "13:7",
    "status": "FINISHED",
    "time": "22-01-2026 12:06",
    "odds": {
      "p1": 1.9,
      "p2": 1.8
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Myst_vs_Glare_22_12",
    "league": "Berserk League",
    "team1": "Myst",
    "team2": "Glare",
    "score": "16:14",
    "status": "FINISHED",
    "time": "22-01-2026 12:01",
    "odds": {
      "p1": 1.62,
      "p2": 2.15
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Glare_vs_Lancer_22_11",
    "league": "Berserk League",
    "team1": "Glare",
    "team2": "Lancer",
    "score": "13:7",
    "status": "FINISHED",
    "time": "22-01-2026 11:12",
    "odds": {
      "p1": 1.85,
      "p2": 1.85
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Myst_vs_Glare_22_11",
    "league": "Berserk League",
    "team1": "Myst",
    "team2": "Glare",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 11:03",
    "odds": {
      "p1": 1.85,
      "p2": 1.85
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "Glare_vs_Lancer_22_10",
    "league": "Berserk League",
    "team1": "Glare",
    "team2": "Lancer",
    "score": "10:13",
    "status": "FINISHED",
    "time": "22-01-2026 10:18",
    "odds": {
      "p1": 1.85,
      "p2": 1.85
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team2"
  },
  {
    "id": "Myst_vs_Glare_22_10",
    "league": "Berserk League",
    "team1": "Myst",
    "team2": "Glare",
    "score": "13:6",
    "status": "FINISHED",
    "time": "22-01-2026 10:09",
    "odds": {
      "p1": 1.62,
      "p2": 2.15
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Myst_vs_Lancer_22_10",
    "league": "Berserk League",
    "team1": "Myst",
    "team2": "Lancer",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 10:00",
    "odds": {
      "p1": 2.35,
      "p2": 1.52
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "Raze_vs_Ignis_22_09",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Ignis",
    "score": "10:13",
    "status": "FINISHED",
    "time": "22-01-2026 09:19",
    "odds": {
      "p1": 1.35,
      "p2": 2.9
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team2"
  },
  {
    "id": "Havoc_vs_Ignis_22_09",
    "league": "Berserk League",
    "team1": "Havoc",
    "team2": "Ignis",
    "score": "13:7",
    "status": "FINISHED",
    "time": "22-01-2026 09:10",
    "odds": {
      "p1": 1.52,
      "p2": 2.35
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Raze_vs_Havoc_22_09",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Havoc",
    "score": "13:8",
    "status": "FINISHED",
    "time": "22-01-2026 09:01",
    "odds": {
      "p1": 1.4,
      "p2": 2.7
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Havoc_vs_Ignis_22_08",
    "league": "Berserk League",
    "team1": "Havoc",
    "team2": "Ignis",
    "score": "6:13",
    "status": "FINISHED",
    "time": "22-01-2026 08:16",
    "odds": {
      "p1": 1.52,
      "p2": 2.35
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team2"
  },
  {
    "id": "Raze_vs_Havoc_22_08",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Havoc",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 08:07",
    "odds": {
      "p1": 1.4,
      "p2": 2.7
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": null
  },
  {
    "id": "Raze_vs_Ignis_22_08",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Ignis",
    "score": "13:9",
    "status": "FINISHED",
    "time": "22-01-2026 08:00",
    "odds": {
      "p1": 1.1,
      "p2": 5.8
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Raze_vs_Havoc_22_07",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Havoc",
    "score": "13:1",
    "status": "FINISHED",
    "time": "22-01-2026 07:40",
    "odds": {
      "p1": 1.42,
      "p2": 2.7
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Raze_vs_Ignis_22_07",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Ignis",
    "score": "5:5",
    "status": "FINISHED",
    "time": "22-01-2026 07:31",
    "odds": {
      "p1": 1.35,
      "p2": 2.9
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": null
  },
  {
    "id": "Havoc_vs_Ignis_22_07",
    "league": "Berserk League",
    "team1": "Havoc",
    "team2": "Ignis",
    "score": "10:13",
    "status": "FINISHED",
    "time": "22-01-2026 07:05",
    "odds": {
      "p1": 1.52,
      "p2": 2.35
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team2"
  },
  {
    "id": "Raze_vs_Ignis_22_06",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Ignis",
    "score": "13:8",
    "status": "FINISHED",
    "time": "22-01-2026 06:20",
    "odds": {
      "p1": 1.38,
      "p2": 2.8
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Havoc_vs_Ignis_22_06",
    "league": "Berserk League",
    "team1": "Havoc",
    "team2": "Ignis",
    "score": "13:11",
    "status": "FINISHED",
    "time": "22-01-2026 06:11",
    "odds": {
      "p1": 1.58,
      "p2": 2.2
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Raze_vs_Havoc_22_06",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Havoc",
    "score": "13:4",
    "status": "FINISHED",
    "time": "22-01-2026 06:02",
    "odds": {
      "p1": 1.4,
      "p2": 2.7
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Havoc_vs_Ignis_22_05",
    "league": "Berserk League",
    "team1": "Havoc",
    "team2": "Ignis",
    "score": "13:7",
    "status": "FINISHED",
    "time": "22-01-2026 05:17",
    "odds": {
      "p1": 1.65,
      "p2": 2.1
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Raze_vs_Havoc_22_05",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Havoc",
    "score": "7:13",
    "status": "FINISHED",
    "time": "22-01-2026 05:08",
    "odds": {
      "p1": 1.42,
      "p2": 2.7
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team2"
  },
  {
    "id": "Raze_vs_Ignis_22_05",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Ignis",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 05:00",
    "odds": {
      "p1": 1.42,
      "p2": 2.7
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "Raze_vs_Ignis_22_04",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Ignis",
    "score": "2:2",
    "status": "FINISHED",
    "time": "22-01-2026 04:15",
    "odds": {
      "p1": 1.4,
      "p2": 2.7
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": null
  },
  {
    "id": "Havoc_vs_Ignis_22_04",
    "league": "Berserk League",
    "team1": "Havoc",
    "team2": "Ignis",
    "score": "9:13",
    "status": "FINISHED",
    "time": "22-01-2026 04:06",
    "odds": {
      "p1": 1.62,
      "p2": 2.15
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team2"
  },
  {
    "id": "Raze_vs_Ignis_22_03",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Ignis",
    "score": "13:9",
    "status": "FINISHED",
    "time": "22-01-2026 03:21",
    "odds": {
      "p1": 1.48,
      "p2": 2.5
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Havoc_vs_Ignis_22_03",
    "league": "Berserk League",
    "team1": "Havoc",
    "team2": "Ignis",
    "score": "13:7",
    "status": "FINISHED",
    "time": "22-01-2026 03:12",
    "odds": {
      "p1": 1.68,
      "p2": 2.05
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Raze_vs_Havoc_22_03",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Havoc",
    "score": "11:3",
    "status": "FINISHED",
    "time": "22-01-2026 03:03",
    "odds": {
      "p1": 1.52,
      "p2": 2.35
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Raze_vs_Havoc_22_02",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Havoc",
    "score": "13:11",
    "status": "FINISHED",
    "time": "22-01-2026 02:09",
    "odds": {
      "p1": 1.02,
      "p2": 11.0
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": "team1"
  },
  {
    "id": "Raze_vs_Ignis_22_02",
    "league": "Berserk League",
    "team1": "Raze",
    "team2": "Ignis",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 02:00",
    "odds": {
      "p1": 1.48,
      "p2": 2.5
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  },
  {
    "id": "Evoker_vs_Zenith_22_01",
    "league": "Berserk League",
    "team1": "Evoker",
    "team2": "Zenith",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 01:19",
    "odds": {
      "p1": 2.1,
      "p2": 1.65
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "3:13"
    },
    "winner": null
  },
  {
    "id": "Vortex_vs_Zenith_22_01",
    "league": "Berserk League",
    "team1": "Vortex",
    "team2": "Zenith",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 01:10",
    "odds": {
      "p1": 1.75,
      "p2": 1.95
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "13:9"
    },
    "winner": null
  },
  {
    "id": "Evoker_vs_Vortex_22_01",
    "league": "Berserk League",
    "team1": "Evoker",
    "team2": "Vortex",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 01:01",
    "odds": {
      "p1": 1.95,
      "p2": 1.75
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "8:13"
    },
    "winner": null
  },
  {
    "id": "Vortex_vs_Zenith_22_00",
    "league": "Berserk League",
    "team1": "Vortex",
    "team2": "Zenith",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 00:16",
    "odds": {
      "p1": 1.72,
      "p2": 2.0
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "5:13"
    },
    "winner": null
  },
  {
    "id": "Evoker_vs_Vortex_22_00",
    "league": "Berserk League",
    "team1": "Evoker",
    "team2": "Vortex",
    "score": "0:0",
    "status": "FINISHED",
    "time": "22-01-2026 00:07",
    "odds": {
      "p1": 1.95,
      "p2": 1.75
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:0"
    },
    "winner": null
  },
  {
    "id": "Evoker_vs_Zenith_21_23",
    "league": "Berserk League",
    "team1": "Evoker",
    "team2": "Zenith",
    "score": "0:0",
    "status": "FINISHED",
    "time": "21-01-2026 23:58",
    "odds": {
      "p1": 2.05,
      "p2": 1.68
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "13:8"
    },
    "winner": null
  },
  {
    "id": "Vortex_vs_Zenith_21_23",
    "league": "Berserk League",
    "team1": "Vortex",
    "team2": "Zenith",
    "score": "13:0",
    "status": "FINISHED",
    "time": "21-01-2026 23:49",
    "odds": {
      "p1": 1.72,
      "p2": 2.0
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:1"
    },
    "winner": "team1"
  },
  {
    "id": "Evoker_vs_Vortex_21_23",
    "league": "Berserk League",
    "team1": "Evoker",
    "team2": "Vortex",
    "score": "13:0",
    "status": "FINISHED",
    "time": "21-01-2026 23:40",
    "odds": {
      "p1": 2.35,
      "p2": 1.52
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {
      "map_1": "0:1"
    },
    "winner": "team1"
  },
  {
    "id": "Evoker_vs_Zenith_21_23",
    "league": "Berserk League",
    "team1": "Evoker",
    "team2": "Zenith",
    "score": "0:0",
    "status": "FINISHED",
    "time": "21-01-2026 23:31",
    "odds": {
      "p1": 3.8,
      "p2": 1.22
    },
    "logos": {
      "t1": "",
      "t2": ""
    },
    "map_scores": {},
    "winner": null
  }
];
const TWITCH_CHANNELS = [];
